version: '3'

services:
  autenticacaoUsuario-api:
    image: node:10.13.0
    environment:
      - NODE_ENV=development
      - PORT=5000
    volumes:
      - './api:/deploy'
    working_dir: '/deploy'
    command: bash -c "npm install && npm run build && node dist/index.js"
    container_name: api
    ports:
      - '5000:5000'

networks:
  default:
    external:
      name: magazinesortimento
